import type { Metadata } from "next";
import "./styles/main.scss";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>zineeworld</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
